// Code generated by "stringer -type=opType"; DO NOT EDIT

package main

import "fmt"

const _opType_name = "opSetopNotopAndopOropLShiftopRShift"

var _opType_index = [...]uint8{0, 5, 10, 15, 19, 27, 35}

func (i opType) String() string {
	if i < 0 || i >= opType(len(_opType_index)-1) {
		return fmt.Sprintf("opType(%d)", i)
	}
	return _opType_name[_opType_index[i]:_opType_index[i+1]]
}
