// Code generated by "stringer -type=Instruction"; DO NOT EDIT

package main

import "fmt"

const _Instruction_name = "turnOnturnOfftoggle"

var _Instruction_index = [...]uint8{0, 6, 13, 19}

func (i Instruction) String() string {
	if i < 0 || i >= Instruction(len(_Instruction_index)-1) {
		return fmt.Sprintf("Instruction(%d)", i)
	}
	return _Instruction_name[_Instruction_index[i]:_Instruction_index[i+1]]
}
