// Code generated by "stringer -type=instruction"; DO NOT EDIT

package main

import "fmt"

const _instruction_name = "turnOnturnOfftoggle"

var _instruction_index = [...]uint8{0, 6, 13, 19}

func (i instruction) String() string {
	if i < 0 || i >= instruction(len(_instruction_index)-1) {
		return fmt.Sprintf("instruction(%d)", i)
	}
	return _instruction_name[_instruction_index[i]:_instruction_index[i+1]]
}
