// Code generated by "stringer -type=opcodeType"; DO NOT EDIT

package main

import "fmt"

const _opcodeType_name = "opHlfopTplopIncopJmpopJieopJio"

var _opcodeType_index = [...]uint8{0, 5, 10, 15, 20, 25, 30}

func (i opcodeType) String() string {
	if i < 0 || i >= opcodeType(len(_opcodeType_index)-1) {
		return fmt.Sprintf("opcodeType(%d)", i)
	}
	return _opcodeType_name[_opcodeType_index[i]:_opcodeType_index[i+1]]
}
