// Code generated by "stringer -type=registerType"; DO NOT EDIT

package main

import "fmt"

const _registerType_name = "regAregB"

var _registerType_index = [...]uint8{0, 4, 8}

func (i registerType) String() string {
	if i < 0 || i >= registerType(len(_registerType_index)-1) {
		return fmt.Sprintf("registerType(%d)", i)
	}
	return _registerType_name[_registerType_index[i]:_registerType_index[i+1]]
}
