// Code generated by "stringer -type=OpType"; DO NOT EDIT

package main

import "fmt"

const _OpType_name = "opSetopNotopAndopOropLShiftopRShift"

var _OpType_index = [...]uint8{0, 5, 10, 15, 19, 27, 35}

func (i OpType) String() string {
	if i < 0 || i >= OpType(len(_OpType_index)-1) {
		return fmt.Sprintf("OpType(%d)", i)
	}
	return _OpType_name[_OpType_index[i]:_OpType_index[i+1]]
}
